// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_common_computecommon.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserType int32

const (
	UserType_ROOT UserType = 0
	UserType_USER UserType = 1
)

var UserType_name = map[int32]string{
	0: "ROOT",
	1: "USER",
}

var UserType_value = map[string]int32{
	"ROOT": 0,
	"USER": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{0}
}

type ProcessorType int32

const (
	ProcessorType_None    ProcessorType = 0
	ProcessorType_Intel   ProcessorType = 1
	ProcessorType_Intel64 ProcessorType = 2
	ProcessorType_AMD     ProcessorType = 3
	ProcessorType_AMD64   ProcessorType = 4
	ProcessorType_ARM     ProcessorType = 5
	ProcessorType_ARM64   ProcessorType = 6
)

var ProcessorType_name = map[int32]string{
	0: "None",
	1: "Intel",
	2: "Intel64",
	3: "AMD",
	4: "AMD64",
	5: "ARM",
	6: "ARM64",
}

var ProcessorType_value = map[string]int32{
	"None":    0,
	"Intel":   1,
	"Intel64": 2,
	"AMD":     3,
	"AMD64":   4,
	"ARM":     5,
	"ARM64":   6,
}

func (x ProcessorType) String() string {
	return proto.EnumName(ProcessorType_name, int32(x))
}

func (ProcessorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{1}
}

type OperatingSystemBootstrapEngine int32

const (
	OperatingSystemBootstrapEngine_CLOUD_INIT           OperatingSystemBootstrapEngine = 0
	OperatingSystemBootstrapEngine_WINDOWS_ANSWER_FILES OperatingSystemBootstrapEngine = 1
)

var OperatingSystemBootstrapEngine_name = map[int32]string{
	0: "CLOUD_INIT",
	1: "WINDOWS_ANSWER_FILES",
}

var OperatingSystemBootstrapEngine_value = map[string]int32{
	"CLOUD_INIT":           0,
	"WINDOWS_ANSWER_FILES": 1,
}

func (x OperatingSystemBootstrapEngine) String() string {
	return proto.EnumName(OperatingSystemBootstrapEngine_name, int32(x))
}

func (OperatingSystemBootstrapEngine) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{2}
}

type OperatingSystemType int32

const (
	OperatingSystemType_WINDOWS OperatingSystemType = 0
	OperatingSystemType_LINUX   OperatingSystemType = 1
)

var OperatingSystemType_name = map[int32]string{
	0: "WINDOWS",
	1: "LINUX",
}

var OperatingSystemType_value = map[string]int32{
	"WINDOWS": 0,
	"LINUX":   1,
}

func (x OperatingSystemType) String() string {
	return proto.EnumName(OperatingSystemType_name, int32(x))
}

func (OperatingSystemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{3}
}

type VirtualMachineSizeType int32

const (
	VirtualMachineSizeType_Default          VirtualMachineSizeType = 0
	VirtualMachineSizeType_Standard_A2_v2   VirtualMachineSizeType = 2
	VirtualMachineSizeType_Standard_A4_v2   VirtualMachineSizeType = 3
	VirtualMachineSizeType_Standard_D2s_v3  VirtualMachineSizeType = 4
	VirtualMachineSizeType_Standard_D4s_v3  VirtualMachineSizeType = 5
	VirtualMachineSizeType_Standard_D8s_v3  VirtualMachineSizeType = 6
	VirtualMachineSizeType_Standard_D16s_v3 VirtualMachineSizeType = 7
	VirtualMachineSizeType_Standard_D32s_v3 VirtualMachineSizeType = 8
	VirtualMachineSizeType_Standard_DS2_v2  VirtualMachineSizeType = 9
	VirtualMachineSizeType_Standard_DS3_v2  VirtualMachineSizeType = 10
	VirtualMachineSizeType_Standard_DS4_v2  VirtualMachineSizeType = 11
	VirtualMachineSizeType_Standard_DS5_v2  VirtualMachineSizeType = 12
	VirtualMachineSizeType_Standard_DS13_v2 VirtualMachineSizeType = 13
	VirtualMachineSizeType_Standard_K8S_v1  VirtualMachineSizeType = 14
	VirtualMachineSizeType_Standard_K8S2_v1 VirtualMachineSizeType = 15
	VirtualMachineSizeType_Standard_K8S3_v1 VirtualMachineSizeType = 16
	VirtualMachineSizeType_Standard_K8S4_v1 VirtualMachineSizeType = 17
	VirtualMachineSizeType_Standard_NK6     VirtualMachineSizeType = 18
	VirtualMachineSizeType_Standard_NK12    VirtualMachineSizeType = 19
	VirtualMachineSizeType_Standard_NV6     VirtualMachineSizeType = 20
	VirtualMachineSizeType_Standard_NV12    VirtualMachineSizeType = 21
	VirtualMachineSizeType_Standard_K8S5_v1 VirtualMachineSizeType = 22
	VirtualMachineSizeType_Custom_NK        VirtualMachineSizeType = 96
	VirtualMachineSizeType_Custom_Gpupv     VirtualMachineSizeType = 97
	VirtualMachineSizeType_Custom           VirtualMachineSizeType = 98
	VirtualMachineSizeType_Unsupported      VirtualMachineSizeType = 99
)

var VirtualMachineSizeType_name = map[int32]string{
	0:  "Default",
	2:  "Standard_A2_v2",
	3:  "Standard_A4_v2",
	4:  "Standard_D2s_v3",
	5:  "Standard_D4s_v3",
	6:  "Standard_D8s_v3",
	7:  "Standard_D16s_v3",
	8:  "Standard_D32s_v3",
	9:  "Standard_DS2_v2",
	10: "Standard_DS3_v2",
	11: "Standard_DS4_v2",
	12: "Standard_DS5_v2",
	13: "Standard_DS13_v2",
	14: "Standard_K8S_v1",
	15: "Standard_K8S2_v1",
	16: "Standard_K8S3_v1",
	17: "Standard_K8S4_v1",
	18: "Standard_NK6",
	19: "Standard_NK12",
	20: "Standard_NV6",
	21: "Standard_NV12",
	22: "Standard_K8S5_v1",
	96: "Custom_NK",
	97: "Custom_Gpupv",
	98: "Custom",
	99: "Unsupported",
}

var VirtualMachineSizeType_value = map[string]int32{
	"Default":          0,
	"Standard_A2_v2":   2,
	"Standard_A4_v2":   3,
	"Standard_D2s_v3":  4,
	"Standard_D4s_v3":  5,
	"Standard_D8s_v3":  6,
	"Standard_D16s_v3": 7,
	"Standard_D32s_v3": 8,
	"Standard_DS2_v2":  9,
	"Standard_DS3_v2":  10,
	"Standard_DS4_v2":  11,
	"Standard_DS5_v2":  12,
	"Standard_DS13_v2": 13,
	"Standard_K8S_v1":  14,
	"Standard_K8S2_v1": 15,
	"Standard_K8S3_v1": 16,
	"Standard_K8S4_v1": 17,
	"Standard_NK6":     18,
	"Standard_NK12":    19,
	"Standard_NV6":     20,
	"Standard_NV12":    21,
	"Standard_K8S5_v1": 22,
	"Custom_NK":        96,
	"Custom_Gpupv":     97,
	"Custom":           98,
	"Unsupported":      99,
}

func (x VirtualMachineSizeType) String() string {
	return proto.EnumName(VirtualMachineSizeType_name, int32(x))
}

func (VirtualMachineSizeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{4}
}

type PowerState int32

const (
	PowerState_Unknown  PowerState = 0
	PowerState_Running  PowerState = 1
	PowerState_Off      PowerState = 2
	PowerState_Paused   PowerState = 3
	PowerState_Critical PowerState = 4
)

var PowerState_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Off",
	3: "Paused",
	4: "Critical",
}

var PowerState_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Off":      2,
	"Paused":   3,
	"Critical": 4,
}

func (x PowerState) String() string {
	return proto.EnumName(PowerState_name, int32(x))
}

func (PowerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{5}
}

type VirtualMachineOperation int32

const (
	VirtualMachineOperation_START VirtualMachineOperation = 0
	VirtualMachineOperation_STOP  VirtualMachineOperation = 1
	VirtualMachineOperation_RESET VirtualMachineOperation = 2
)

var VirtualMachineOperation_name = map[int32]string{
	0: "START",
	1: "STOP",
	2: "RESET",
}

var VirtualMachineOperation_value = map[string]int32{
	"START": 0,
	"STOP":  1,
	"RESET": 2,
}

func (x VirtualMachineOperation) String() string {
	return proto.EnumName(VirtualMachineOperation_name, int32(x))
}

func (VirtualMachineOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{6}
}

type VirtualMachineCustomSize struct {
	CpuCount             int32    `protobuf:"varint,1,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	MemoryMB             int32    `protobuf:"varint,2,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	GpuCount             int32    `protobuf:"varint,3,opt,name=gpuCount,proto3" json:"gpuCount,omitempty"`
	GpuName              string   `protobuf:"bytes,4,opt,name=gpuName,proto3" json:"gpuName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualMachineCustomSize) Reset()         { *m = VirtualMachineCustomSize{} }
func (m *VirtualMachineCustomSize) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineCustomSize) ProtoMessage()    {}
func (*VirtualMachineCustomSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{0}
}

func (m *VirtualMachineCustomSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineCustomSize.Unmarshal(m, b)
}
func (m *VirtualMachineCustomSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineCustomSize.Marshal(b, m, deterministic)
}
func (m *VirtualMachineCustomSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineCustomSize.Merge(m, src)
}
func (m *VirtualMachineCustomSize) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineCustomSize.Size(m)
}
func (m *VirtualMachineCustomSize) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineCustomSize.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineCustomSize proto.InternalMessageInfo

func (m *VirtualMachineCustomSize) GetCpuCount() int32 {
	if m != nil {
		return m.CpuCount
	}
	return 0
}

func (m *VirtualMachineCustomSize) GetMemoryMB() int32 {
	if m != nil {
		return m.MemoryMB
	}
	return 0
}

func (m *VirtualMachineCustomSize) GetGpuCount() int32 {
	if m != nil {
		return m.GpuCount
	}
	return 0
}

func (m *VirtualMachineCustomSize) GetGpuName() string {
	if m != nil {
		return m.GpuName
	}
	return ""
}

func init() {
	proto.RegisterEnum("moc.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("moc.ProcessorType", ProcessorType_name, ProcessorType_value)
	proto.RegisterEnum("moc.OperatingSystemBootstrapEngine", OperatingSystemBootstrapEngine_name, OperatingSystemBootstrapEngine_value)
	proto.RegisterEnum("moc.OperatingSystemType", OperatingSystemType_name, OperatingSystemType_value)
	proto.RegisterEnum("moc.VirtualMachineSizeType", VirtualMachineSizeType_name, VirtualMachineSizeType_value)
	proto.RegisterEnum("moc.PowerState", PowerState_name, PowerState_value)
	proto.RegisterEnum("moc.VirtualMachineOperation", VirtualMachineOperation_name, VirtualMachineOperation_value)
	proto.RegisterType((*VirtualMachineCustomSize)(nil), "moc.VirtualMachineCustomSize")
}

func init() { proto.RegisterFile("moc_common_computecommon.proto", fileDescriptor_7d1a061f6c82445b) }

var fileDescriptor_7d1a061f6c82445b = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x94, 0xdb, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0x31, 0x67, 0x86, 0x90, 0x4c, 0x36, 0x69, 0x8a, 0x7a, 0x11, 0x45, 0xad, 0x2a, 0x45,
	0x48, 0x0d, 0xe2, 0x10, 0x94, 0x5e, 0x12, 0xa0, 0x15, 0x25, 0x18, 0x64, 0x43, 0xd2, 0xf6, 0xc6,
	0x75, 0xcc, 0x42, 0xac, 0xe2, 0x5d, 0xcb, 0x5e, 0x13, 0xa5, 0x4f, 0xd0, 0x37, 0xe8, 0xeb, 0x56,
	0x6b, 0x03, 0xad, 0x7d, 0xe5, 0xfd, 0xbf, 0x99, 0xf9, 0x77, 0xe4, 0x9d, 0x5d, 0x38, 0x77, 0xb8,
	0x65, 0x58, 0xdc, 0x71, 0x38, 0x93, 0x1f, 0x37, 0x10, 0x34, 0x52, 0x57, 0xae, 0xc7, 0x05, 0x27,
	0x19, 0x87, 0x5b, 0x6f, 0x7f, 0x2b, 0x50, 0xbd, 0xb7, 0x3d, 0x11, 0x98, 0xeb, 0xb1, 0x69, 0x3d,
	0xd9, 0x8c, 0xf6, 0x02, 0x5f, 0x70, 0x47, 0xb7, 0x7f, 0x51, 0xf2, 0x06, 0x8a, 0x96, 0x1b, 0xf4,
	0x78, 0xc0, 0x44, 0x55, 0xb9, 0x50, 0x2e, 0x73, 0xda, 0x5e, 0xcb, 0x98, 0x43, 0x1d, 0xee, 0xbd,
	0x8c, 0x6f, 0xab, 0xe9, 0x28, 0xb6, 0xd3, 0x32, 0xb6, 0xda, 0xd5, 0x65, 0xa2, 0xd8, 0x4e, 0x93,
	0x2a, 0x14, 0x56, 0x6e, 0xa0, 0x9a, 0x0e, 0xad, 0x66, 0x2f, 0x94, 0xcb, 0x92, 0xb6, 0x93, 0xb5,
	0x73, 0x28, 0xce, 0x7d, 0xea, 0xcd, 0x5e, 0x5c, 0x4a, 0x8a, 0x90, 0xd5, 0x26, 0x93, 0x19, 0xa6,
	0xe4, 0x6a, 0xae, 0x0f, 0x34, 0x54, 0x6a, 0xdf, 0xa0, 0x32, 0xf5, 0xb8, 0x45, 0x7d, 0x9f, 0xef,
	0x93, 0x54, 0xce, 0x28, 0xa6, 0x48, 0x09, 0x72, 0x43, 0x26, 0xe8, 0x1a, 0x15, 0x52, 0x86, 0x42,
	0xb8, 0xec, 0xb4, 0x31, 0x4d, 0x0a, 0x90, 0xe9, 0x8e, 0xfb, 0x98, 0x91, 0x09, 0xdd, 0x71, 0xbf,
	0xd3, 0xc6, 0x6c, 0xc8, 0xb4, 0x31, 0xe6, 0x42, 0xa6, 0x8d, 0x3b, 0x6d, 0xcc, 0xd7, 0xbe, 0xc0,
	0xf9, 0xc4, 0xa5, 0x9e, 0x29, 0x6c, 0xb6, 0xd2, 0x5f, 0x7c, 0x41, 0x9d, 0x5b, 0xce, 0x85, 0x2f,
	0x3c, 0xd3, 0x1d, 0xb0, 0x95, 0xcd, 0x28, 0x39, 0x04, 0xe8, 0xdd, 0x4d, 0xe6, 0x7d, 0x63, 0xa8,
	0x0e, 0x65, 0x5b, 0x55, 0x38, 0x7d, 0x18, 0xaa, 0xfd, 0xc9, 0x83, 0x6e, 0x74, 0x55, 0xfd, 0x61,
	0xa0, 0x19, 0x9f, 0x86, 0x77, 0x03, 0x1d, 0x95, 0xda, 0x07, 0x38, 0x49, 0x78, 0x85, 0xcd, 0x96,
	0xa1, 0xb0, 0x2d, 0x88, 0xfa, 0xbd, 0x1b, 0xaa, 0xf3, 0xaf, 0xa8, 0xd4, 0xfe, 0x64, 0xe1, 0x2c,
	0x7e, 0x00, 0xf2, 0xd7, 0xef, 0x4a, 0xfa, 0x74, 0x69, 0x06, 0x6b, 0x81, 0x29, 0x42, 0xe0, 0x50,
	0x17, 0x26, 0x5b, 0x98, 0xde, 0xc2, 0xe8, 0x36, 0x8d, 0x4d, 0x13, 0xd3, 0x71, 0xd6, 0x96, 0x2c,
	0x43, 0x4e, 0xe0, 0x68, 0xcf, 0xfa, 0x4d, 0xdf, 0xd8, 0xb4, 0x30, 0x1b, 0x87, 0xed, 0x10, 0xe6,
	0xe2, 0xf0, 0x26, 0x84, 0x79, 0x72, 0x0a, 0xf8, 0x0f, 0x36, 0x3a, 0x21, 0x2d, 0xc4, 0x69, 0x2b,
	0x72, 0x2d, 0xc6, 0x0d, 0xf4, 0xb0, 0xa7, 0x52, 0x02, 0xb6, 0x24, 0x84, 0x04, 0x0c, 0x3b, 0x2d,
	0x27, 0xe0, 0xb5, 0x84, 0x07, 0xf1, 0x9d, 0xf4, 0x46, 0x58, 0x5f, 0x89, 0xa5, 0x8e, 0x6e, 0x74,
	0x63, 0xd3, 0xc0, 0xc3, 0x58, 0xea, 0xe8, 0x46, 0xee, 0xdf, 0xc0, 0xa3, 0x24, 0x6d, 0x49, 0x8a,
	0x49, 0xda, 0x96, 0xf4, 0x98, 0x20, 0x1c, 0xec, 0xa9, 0x3a, 0xea, 0x20, 0x21, 0xc7, 0x50, 0xf9,
	0x8f, 0x34, 0x9a, 0x78, 0x12, 0x4f, 0xba, 0xef, 0xe0, 0x69, 0x3c, 0xe9, 0xbe, 0xd1, 0xc4, 0x57,
	0x49, 0xff, 0x6b, 0xe9, 0x7f, 0x46, 0x2a, 0x50, 0x8a, 0x6e, 0x93, 0xa1, 0x8e, 0xf0, 0x87, 0x74,
	0xda, 0xca, 0xcf, 0x6e, 0xe0, 0x6e, 0xd0, 0x24, 0x00, 0xf9, 0x88, 0xe0, 0x23, 0x39, 0x82, 0xf2,
	0x9c, 0xf9, 0x81, 0xeb, 0x72, 0x4f, 0xd0, 0x05, 0x5a, 0xb5, 0x21, 0xc0, 0x94, 0x3f, 0x53, 0x4f,
	0x17, 0xa6, 0x08, 0x87, 0x61, 0xce, 0x7e, 0x32, 0xfe, 0xcc, 0x30, 0x25, 0x85, 0x16, 0x30, 0x66,
	0xb3, 0x15, 0x2a, 0x72, 0xa0, 0x27, 0xcb, 0x25, 0xa6, 0xa5, 0xdb, 0xd4, 0x0c, 0x7c, 0xba, 0xc0,
	0x0c, 0x39, 0x80, 0x62, 0xcf, 0xb3, 0x85, 0x6d, 0x99, 0x6b, 0xcc, 0xd6, 0x3e, 0xc2, 0xeb, 0xf8,
	0x8c, 0x6d, 0x27, 0x94, 0x33, 0x39, 0x8a, 0xfa, 0xac, 0xab, 0x6d, 0xaf, 0x9a, 0x3e, 0x9b, 0x4c,
	0x51, 0x91, 0x50, 0x1b, 0xe8, 0x83, 0x19, 0xa6, 0x6f, 0xdf, 0x7f, 0x7f, 0xb7, 0xb2, 0xc5, 0x53,
	0xf0, 0x78, 0x65, 0x71, 0xa7, 0xee, 0xd8, 0x96, 0xc7, 0x7d, 0xbe, 0x14, 0x75, 0x87, 0x5b, 0x75,
	0xcf, 0xb5, 0xea, 0xd1, 0x93, 0xf2, 0x98, 0x0f, 0xdf, 0x94, 0xd6, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x32, 0x11, 0x49, 0x46, 0x75, 0x04, 0x00, 0x00,
}
