// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_nodeagent_sharedfolder.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SharedFolderRequest struct {
	SharedFolderSystems  []*SharedFolder  `protobuf:"bytes,1,rep,name=SharedFolderSystems,proto3" json:"SharedFolderSystems,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SharedFolderRequest) Reset()         { *m = SharedFolderRequest{} }
func (m *SharedFolderRequest) String() string { return proto.CompactTextString(m) }
func (*SharedFolderRequest) ProtoMessage()    {}
func (*SharedFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db807b23661f235a, []int{0}
}

func (m *SharedFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedFolderRequest.Unmarshal(m, b)
}
func (m *SharedFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedFolderRequest.Marshal(b, m, deterministic)
}
func (m *SharedFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedFolderRequest.Merge(m, src)
}
func (m *SharedFolderRequest) XXX_Size() int {
	return xxx_messageInfo_SharedFolderRequest.Size(m)
}
func (m *SharedFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SharedFolderRequest proto.InternalMessageInfo

func (m *SharedFolderRequest) GetSharedFolderSystems() []*SharedFolder {
	if m != nil {
		return m.SharedFolderSystems
	}
	return nil
}

func (m *SharedFolderRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type SharedFolderResponse struct {
	SharedFolderSystems  []*SharedFolder     `protobuf:"bytes,1,rep,name=SharedFolderSystems,proto3" json:"SharedFolderSystems,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SharedFolderResponse) Reset()         { *m = SharedFolderResponse{} }
func (m *SharedFolderResponse) String() string { return proto.CompactTextString(m) }
func (*SharedFolderResponse) ProtoMessage()    {}
func (*SharedFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db807b23661f235a, []int{1}
}

func (m *SharedFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedFolderResponse.Unmarshal(m, b)
}
func (m *SharedFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedFolderResponse.Marshal(b, m, deterministic)
}
func (m *SharedFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedFolderResponse.Merge(m, src)
}
func (m *SharedFolderResponse) XXX_Size() int {
	return xxx_messageInfo_SharedFolderResponse.Size(m)
}
func (m *SharedFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SharedFolderResponse proto.InternalMessageInfo

func (m *SharedFolderResponse) GetSharedFolderSystems() []*SharedFolder {
	if m != nil {
		return m.SharedFolderSystems
	}
	return nil
}

func (m *SharedFolderResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *SharedFolderResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SharedFolder struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Hostpath             string         `protobuf:"bytes,3,opt,name=hostpath,proto3" json:"hostpath,omitempty"`
	Readonly             bool           `protobuf:"varint,4,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Guestmountpath       string         `protobuf:"bytes,5,opt,name=guestmountpath,proto3" json:"guestmountpath,omitempty"`
	VirtualmachineName   string         `protobuf:"bytes,6,opt,name=virtualmachineName,proto3" json:"virtualmachineName,omitempty"`
	Status               *common.Status `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *common.Entity `protobuf:"bytes,8,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                 *common.Tags   `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SharedFolder) Reset()         { *m = SharedFolder{} }
func (m *SharedFolder) String() string { return proto.CompactTextString(m) }
func (*SharedFolder) ProtoMessage()    {}
func (*SharedFolder) Descriptor() ([]byte, []int) {
	return fileDescriptor_db807b23661f235a, []int{2}
}

func (m *SharedFolder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedFolder.Unmarshal(m, b)
}
func (m *SharedFolder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedFolder.Marshal(b, m, deterministic)
}
func (m *SharedFolder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedFolder.Merge(m, src)
}
func (m *SharedFolder) XXX_Size() int {
	return xxx_messageInfo_SharedFolder.Size(m)
}
func (m *SharedFolder) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedFolder.DiscardUnknown(m)
}

var xxx_messageInfo_SharedFolder proto.InternalMessageInfo

func (m *SharedFolder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SharedFolder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SharedFolder) GetHostpath() string {
	if m != nil {
		return m.Hostpath
	}
	return ""
}

func (m *SharedFolder) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

func (m *SharedFolder) GetGuestmountpath() string {
	if m != nil {
		return m.Guestmountpath
	}
	return ""
}

func (m *SharedFolder) GetVirtualmachineName() string {
	if m != nil {
		return m.VirtualmachineName
	}
	return ""
}

func (m *SharedFolder) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SharedFolder) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *SharedFolder) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*SharedFolderRequest)(nil), "moc.nodeagent.storage.SharedFolderRequest")
	proto.RegisterType((*SharedFolderResponse)(nil), "moc.nodeagent.storage.SharedFolderResponse")
	proto.RegisterType((*SharedFolder)(nil), "moc.nodeagent.storage.SharedFolder")
}

func init() { proto.RegisterFile("moc_nodeagent_sharedfolder.proto", fileDescriptor_db807b23661f235a) }

var fileDescriptor_db807b23661f235a = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xff, 0x4e, 0xd3, 0xfc, 0x93, 0x0d, 0x44, 0xea, 0x52, 0xc0, 0x18, 0x15, 0x45, 0xa9,
	0x84, 0x22, 0x90, 0xd6, 0x28, 0xf0, 0x02, 0x14, 0x05, 0xc1, 0xa5, 0x48, 0x4e, 0xe1, 0xc0, 0xa5,
	0xda, 0xac, 0x27, 0xb6, 0x55, 0xef, 0x8e, 0xd9, 0x5d, 0x17, 0xe5, 0x75, 0xb8, 0xf2, 0x00, 0xdc,
	0x79, 0x32, 0xe4, 0xb5, 0x31, 0x4e, 0xc9, 0xa1, 0x17, 0x4e, 0xc9, 0xce, 0xf7, 0x9b, 0xcf, 0x9f,
	0x67, 0xbc, 0x64, 0x2a, 0x51, 0x5c, 0x2a, 0x8c, 0x81, 0x27, 0xa0, 0xec, 0xa5, 0x49, 0xb9, 0x86,
	0x78, 0x83, 0x79, 0x0c, 0x9a, 0x15, 0x1a, 0x2d, 0xd2, 0xfb, 0x12, 0x05, 0x6b, 0x09, 0x66, 0x2c,
	0x6a, 0x9e, 0x40, 0xf0, 0x24, 0x41, 0x4c, 0x72, 0x08, 0x1d, 0xb4, 0x2e, 0x37, 0xe1, 0x57, 0xcd,
	0x8b, 0x02, 0xb4, 0xa9, 0xdb, 0x82, 0x87, 0x95, 0xb1, 0x40, 0x29, 0x51, 0x35, 0x3f, 0x8d, 0x70,
	0xd2, 0x11, 0x14, 0xda, 0x6c, 0x93, 0x09, 0x6e, 0xb3, 0x56, 0x7e, 0x7c, 0xd3, 0x17, 0x64, 0x61,
	0xb7, 0xb5, 0x38, 0xfb, 0xe6, 0x91, 0x7b, 0x2b, 0x17, 0xf1, 0xad, 0x8b, 0x18, 0xc1, 0x97, 0x12,
	0x8c, 0xa5, 0x1f, 0x77, 0xcb, 0xab, 0xad, 0xb1, 0x20, 0x8d, 0xef, 0x4d, 0x0f, 0xe6, 0xe3, 0xc5,
	0x29, 0xdb, 0xfb, 0x06, 0x6c, 0xc7, 0x68, 0x5f, 0x3f, 0x7d, 0x45, 0xee, 0x7e, 0x28, 0x40, 0xbb,
	0x78, 0x17, 0xdb, 0x02, 0xfc, 0xde, 0xd4, 0x9b, 0x4f, 0x16, 0x13, 0x67, 0xd8, 0x2a, 0xd1, 0x2e,
	0x34, 0xfb, 0xe1, 0x91, 0xe3, 0xdd, 0x90, 0xa6, 0x40, 0x65, 0xe0, 0x5f, 0xa5, 0x5c, 0x90, 0x41,
	0x04, 0xa6, 0xcc, 0xad, 0x8b, 0x37, 0x5e, 0x04, 0xac, 0x1e, 0x21, 0xfb, 0x3d, 0x42, 0x76, 0x86,
	0x98, 0x7f, 0xe2, 0x79, 0x09, 0x51, 0x43, 0xd2, 0x63, 0x72, 0xb8, 0xd4, 0x1a, 0xb5, 0x7f, 0x30,
	0xf5, 0xe6, 0xa3, 0xa8, 0x3e, 0xcc, 0xbe, 0xf7, 0xc8, 0x9d, 0xee, 0x13, 0x28, 0x25, 0x7d, 0xc5,
	0x25, 0xf8, 0x9e, 0xa3, 0xdc, 0x7f, 0x3a, 0x21, 0xbd, 0x2c, 0x76, 0x8f, 0x1a, 0x45, 0xbd, 0x2c,
	0xa6, 0x01, 0x19, 0xa6, 0x68, 0x6c, 0xc1, 0x6d, 0xda, 0xb8, 0xb5, 0xe7, 0x4a, 0xd3, 0xc0, 0x63,
	0x54, 0xf9, 0xd6, 0xef, 0x4f, 0xbd, 0xf9, 0x30, 0x6a, 0xcf, 0xf4, 0x29, 0x99, 0x24, 0xd5, 0xf2,
	0x24, 0x96, 0xaa, 0xee, 0x3e, 0x74, 0xdd, 0x37, 0xaa, 0x94, 0x11, 0x7a, 0x9d, 0x69, 0x5b, 0xf2,
	0x5c, 0x72, 0x91, 0x66, 0x0a, 0xce, 0xab, 0x44, 0x03, 0xc7, 0xee, 0x51, 0xe8, 0x29, 0x19, 0x18,
	0xcb, 0x6d, 0x69, 0xfc, 0xff, 0xdd, 0x38, 0xc6, 0x6e, 0xb0, 0x2b, 0x57, 0x8a, 0x1a, 0xa9, 0x82,
	0x40, 0xd9, 0xcc, 0x6e, 0xfd, 0x61, 0x07, 0x5a, 0xba, 0x52, 0xd4, 0x48, 0xf4, 0x84, 0xf4, 0x2d,
	0x4f, 0x8c, 0x3f, 0x72, 0xc8, 0xc8, 0x21, 0x17, 0x3c, 0x31, 0x91, 0x2b, 0x2f, 0x7e, 0x7a, 0xe4,
	0xa8, 0x3b, 0xad, 0xd7, 0xd5, 0xde, 0xa8, 0x20, 0x83, 0xf7, 0xea, 0x1a, 0xaf, 0x80, 0x3e, 0xbb,
	0xcd, 0x46, 0xeb, 0x0f, 0x38, 0x78, 0x7e, 0x2b, 0xb6, 0xfe, 0x8e, 0x66, 0xff, 0xd1, 0x77, 0xe4,
	0xe8, 0x4d, 0x0a, 0xe2, 0xea, 0xbc, 0x73, 0x7f, 0xe8, 0x83, 0xbf, 0xf6, 0xbe, 0xac, 0xae, 0x4e,
	0xf0, 0xc8, 0x79, 0x77, 0xd1, 0x3f, 0x4e, 0x67, 0x2f, 0x3e, 0xb3, 0x24, 0xb3, 0x69, 0xb9, 0x66,
	0x02, 0x65, 0x28, 0x33, 0xa1, 0xd1, 0xe0, 0xc6, 0x86, 0x12, 0x45, 0xa8, 0x0b, 0x11, 0xb6, 0x91,
	0xc2, 0x26, 0xd2, 0x7a, 0xe0, 0xec, 0x5f, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x46, 0x9d, 0x43,
	0x8e, 0x3a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SharedFolderAgentClient is the client API for SharedFolderAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SharedFolderAgentClient interface {
	Invoke(ctx context.Context, in *SharedFolderRequest, opts ...grpc.CallOption) (*SharedFolderResponse, error)
	CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error)
}

type sharedFolderAgentClient struct {
	cc *grpc.ClientConn
}

func NewSharedFolderAgentClient(cc *grpc.ClientConn) SharedFolderAgentClient {
	return &sharedFolderAgentClient{cc}
}

func (c *sharedFolderAgentClient) Invoke(ctx context.Context, in *SharedFolderRequest, opts ...grpc.CallOption) (*SharedFolderResponse, error) {
	out := new(SharedFolderResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.storage.SharedFolderAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharedFolderAgentClient) CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error) {
	out := new(common.NotificationResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.storage.SharedFolderAgent/CheckNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharedFolderAgentServer is the server API for SharedFolderAgent service.
type SharedFolderAgentServer interface {
	Invoke(context.Context, *SharedFolderRequest) (*SharedFolderResponse, error)
	CheckNotification(context.Context, *empty.Empty) (*common.NotificationResponse, error)
}

// UnimplementedSharedFolderAgentServer can be embedded to have forward compatible implementations.
type UnimplementedSharedFolderAgentServer struct {
}

func (*UnimplementedSharedFolderAgentServer) Invoke(ctx context.Context, req *SharedFolderRequest) (*SharedFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedSharedFolderAgentServer) CheckNotification(ctx context.Context, req *empty.Empty) (*common.NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNotification not implemented")
}

func RegisterSharedFolderAgentServer(s *grpc.Server, srv SharedFolderAgentServer) {
	s.RegisterService(&_SharedFolderAgent_serviceDesc, srv)
}

func _SharedFolderAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharedFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedFolderAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.storage.SharedFolderAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedFolderAgentServer).Invoke(ctx, req.(*SharedFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharedFolderAgent_CheckNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedFolderAgentServer).CheckNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.storage.SharedFolderAgent/CheckNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedFolderAgentServer).CheckNotification(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SharedFolderAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.nodeagent.storage.SharedFolderAgent",
	HandlerType: (*SharedFolderAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _SharedFolderAgent_Invoke_Handler,
		},
		{
			MethodName: "CheckNotification",
			Handler:    _SharedFolderAgent_CheckNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_nodeagent_sharedfolder.proto",
}
